version: '3.8'

services:
  bot:
    build: .
    container_name: mavryk-wallet
    stop_signal: SIGINT
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
